# Indexing and Selection

Let's have a look into how we can select a group of elements from an array

### We need to import the numpy library as always

In [1]:
import numpy as np

In [2]:
array = np.arange(15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Indexing

Selecting an element from an array:

In [3]:
array[0]   # first value, index = 0

0

In [4]:
array[-1]   # last value, index = -1

14

Selecting a group of elements from an array:

In [5]:
array[0:5]  # selecting the elements from 0 until 5 [0,5)

array([0, 1, 2, 3, 4])

In [6]:
array[6:11]

array([ 6,  7,  8,  9, 10])

Indexing using different methods:

In [7]:
array[9:-1:2] 

array([ 9, 11, 13])

In [8]:
array[9:15:2]

array([ 9, 11, 13])

In [9]:
array[9::2]

array([ 9, 11, 13])

In [10]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
array[0:5] = 11
array

array([11, 11, 11, 11, 11,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
array = np.arange(15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
part_array = array[0:3]
part_array

array([0, 1, 2])

In [14]:
part_array[:] = 11
part_array

array([11, 11, 11])

#### Important:
     Modifications done to the array piece selected also effects the original array!

In [15]:
array

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

It is always safer to work on the copy of an original array unless we really want to modify the original array.

In [16]:
copy_array = array[0:3].copy()
copy_array

array([11, 11, 11])

In [17]:
copy_array[:] = 111
copy_array

array([111, 111, 111])

In [18]:
array

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 2D arrays

Let's have a look at indexing with 2D arrays

In [19]:
array_2d = np.array(([0,1,2],[10,11,12],[20,30,40]))
array_2d

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 30, 40]])

In [20]:
array_2d[0]

array([0, 1, 2])

In [21]:
array_2d[1]

array([10, 11, 12])

In [22]:
array_2d[0][0]

0

In [23]:
array_2d[1,1]

11

In [24]:
array_2d[1:,1:]

array([[11, 12],
       [30, 40]])

In [25]:
array_2d[:2,:2]

array([[ 0,  1],
       [10, 11]])

In [26]:
array_2d = np.arange(25).reshape(5,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
array_2d[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
array_2d[[0,2]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [29]:
array_2d[:,[0,2]]

array([[ 0,  2],
       [ 5,  7],
       [10, 12],
       [15, 17],
       [20, 22]])

## Selection
Selection from an array using logical conditions:

In [30]:
array

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
array > 10

array([ True,  True,  True, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True])

In [32]:
filter_array = array >10
filter_array

array([ True,  True,  True, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True])

In [33]:
array[filter_array]

array([11, 11, 11, 11, 12, 13, 14])